### ISSUE TITLE
Disabling metrics-servers braking the vector installation

### ISSUE THREAD

**Issue by gordonswing** [BetterStackHQ/logs-helm-chart#13]
**Disabling the metrics-server in values.yaml leading to constant errors** 
When I'm disabling metrics server, there is no templates files to overdue lack of DNS for `metrics-server`.

So, in the current implementation I cannot run only vector without installing `metrics-server`.

```
2024-12-16T16:05:49.005504Z WARN source{component_kind="source" component_id=better_stack_kubernetes_metrics_pods component_type=http_client}:http: vector::internal_events::http_client: HTTP error. error=error trying to connect: dns error: failed to lookup address information: Name or service not known error_type="request_failed" stage="processing" internal_log_rate_limit=true
```

In addition, omitting the section leads to this error:
```
    sinks:
        better_stack_http_metrics_sink:
          auth:
            token: ""
```
            
```
2024-12-16T14:59:27.111378Z ERROR vector::cli: Configuration error. error=sinks.better_stack_http_metrics_sink.auth.token: invalid type: unit value, expected any valid TOML value at line 6 column 14
```

**Comment by PetrHeinz** [comment]
Hi @gordonswing, and thanks for reaching out! 🙌 

You can run the Helm chart without metrics-server, but the metrics pipeline needs to be disabled within Vector configuration. You can remove any value in you `values.yaml` by setting it to `NULL`, which is done using `~` in YAML.

Specifically, the `values.yaml` with fully disabled metrics collection would look like this:

```yaml
vector:
  customConfig:
    sinks:
      better_stack_http_sink:
        auth:
          token: $SOURCE_TOKEN
      better_stack_http_metrics_sink: ~
    sources:
      better_stack_kubernetes_metrics_nodes: ~
      better_stack_kubernetes_metrics_pods: ~
    transforms:
      better_stack_kubernetes_metrics_nodes_parser: ~
      better_stack_kubernetes_metrics_pods_parser: ~

metrics-server:
  enabled: false
```

That should run without any metrics-related errors, as the whole metrics pipeline is removed form Vector configuration.

Hope this helps! 🙌
