### ISSUE TITLE
Unable to Install Betterstack

### ISSUE THREAD

**Issue by riteshsonawane1372** [BetterStackHQ/logs-helm-chart#2]
I used Helm for installation of betterstack on my cluster but I encountered an error `Error: INSTALLATION FAILED: rendered manifests contain a resource that already exists. Unable to continue with install: ClusterRole "system:metrics-server-aggregated-reader" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; annotation validation error: key "meta.helm.sh/release-name" must equal "betterstack-logs": current value is "metrics-server"; annotation validation error: key "meta.helm.sh/release-namespace" must equal "default": current value is "kube-system"
`

**Comment by gyfis** [comment]
Hi @riteshsonawane1372, thanks for the report. Seems something is off, since the helm chart works fine for us. Can you share your full helm charts & configs, please?

**Comment by riteshsonawane1372** [comment]
> Hi @riteshsonawane1372, thanks for the report. Seems something is off, since the helm chart works fine for us. Can you share your full helm charts & configs, please?

`helm repo add betterstack-logs https://betterstackhq.github.io/logs-helm-chart`
`helm repo update`
 This was the chart I used. When I tested betterstack on my local cluster `minikube`. It was running fine, I was able to see the logs, but when I tested it on a production EKS cluster I got the above [error](https://github.com/BetterStackHQ/logs-helm-chart/issues/2#issue-1951581190) .  This was the values.yaml file
```
metrics-server:
  enabled: true
vector:
  customConfig:
    sinks:
      better_stack_http_sink:
        auth: $TOKEN
          token: 
      better_stack_http_metrics_sink:
        auth:
          token: $TOKEN
```
I also test it by removing `metrics-server:
  enabled: true`
