### ISSUE TITLE
Unable to install Helm Chart - secrets "vector-service-account" not found

### ISSUE THREAD

**Issue by tomsjansons** [BetterStackHQ/logs-helm-chart#20]
I am running a standard install of k3s locally and attempting to install the better stack helm chart with Pulumi.
When running pulumi up, the chart fails to deploy because it fails to create secret 'vector-service-account' secret and then dependent resources fail because the secret is missing: `secrets "vector-service-account" not found`

```ts
import * as k8s from "@pulumi/kubernetes";
import * as pulumi from "@pulumi/pulumi";

const config = new pulumi.Config();
const logsUri = config.require("better_stack_logs_uri");
const metricsUri = config.require("better_stack_metrics_uri");
const token = config.requireSecret("better_stack_token");

const namespaceName = "better-stack";
const betterStackNamespace = new k8s.core.v1.Namespace(namespaceName, {
  metadata: {
    name: namespaceName,
  },
});

new k8s.helm.v4.Chart("betterstack-vector", {
  chart: "betterstack-logs",
  namespace: betterStackNamespace.metadata.name,
  repositoryOpts: {
    repo: "https://betterstackhq.github.io/logs-helm-chart",
  },
  values: {
    vector: {
      customConfig: {
        sinks: {
          better_stack_http_sink: {
            uri: logsUri,
            auth: {
              strategy: "bearer",
              token,
            },
          },
          better_stack_http_metrics_sink: {
            uri: metricsUri,
            auth: {
              strategy: "bearer",
              token,
            },
          },
        },
      },
    },
  },
});

```

![Image](https://github.com/user-attachments/assets/fd0dd49e-61f5-4796-89ec-c4cff2f5a431)

```
k3s version v1.31.5+k3s1 (56ec5dd4)
go version go1.22.10
```

I am unfortunately unable to find any additional logs as the secret just does not exist

To determine if Pulumi is the problem or something else, I tried installing with helm directly, I'm getting the following error. Same error with or without specifying a custom namespace

```bash
toms@ridi-dev:~/dev/ridi-apps/infra$ helm install betterstack-logs betterstack-logs/betterstack-logs -f values.yaml --namespace better-stack --create-namespace
Error: INSTALLATION FAILED: Unable to continue with install: APIService "v1beta1.metrics.k8s.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "betterstack-logs"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "better-stack"
```

```bash
toms@ridi-dev:~/dev/ridi-apps/infra$ helm install betterstack-logs betterstack-logs/betterstack-logs -f values.yaml
Error: INSTALLATION FAILED: Unable to continue with install: APIService "v1beta1.metrics.k8s.io" in namespace "" exists and cannot be imported into the current release: invalid ownership metadata; label validation error: missing key "app.kubernetes.io/managed-by": must be set to "Helm"; annotation validation error: missing key "meta.helm.sh/release-name": must be set to "betterstack-logs"; annotation validation error: missing key "meta.helm.sh/release-namespace": must be set to "default"
```

At this point I'm a bit stuck as I'm unsure about any further debug steps. 
Any help would be appreciated!

**Comment by PetrHeinz** [comment]
Hello @tomsjansons, thanks for reaching out! 🙌 

Looking at the error messages from Helm, it seems that you have your metrics-server already installed. You can try installing the Helm chart without the included metric-server:

```cmd
helm install betterstack-logs betterstack-logs/betterstack-logs -f values.yaml \
  --set metrics-server.enabled=false
```

It might need some tweaking in case your metrics-server is in a different namespace, or uses self-signed certificates. You can try specifying the exact endpoints and disabling TLS verification in your `values.yaml` in that case, and installing the chart as usual:

```yaml
vector:
  customConfig:
    sinks:
      better_stack_http_sink:
        uri: "https://$INGESTING_HOST/"
        auth:
          strategy: "bearer"
          token: "$SOURCE_TOKEN"
      better_stack_http_metrics_sink:
        uri: "https://$INGESTING_HOST/metrics"
        auth:
          strategy: "bearer"
          token: "$SOURCE_TOKEN"
    sources:
      better_stack_kubernetes_metrics_nodes:
        endpoint: "https://metrics-server.kube-system/apis/metrics.k8s.io/v1beta1/nodes"
        tls:
          verify_certificate: false
          verify_hostname: false
      better_stack_kubernetes_metrics_pods:
        endpoint: "https://metrics-server.kube-system/apis/metrics.k8s.io/v1beta1/pods"
        tls:
          verify_certificate: false
          verify_hostname: false

# Metrics server is already installed
metrics-server:
  enabled: false
```

Hope this helps 🙌 

Please let me know if you were able to send your Kubernetes logs and metrics top Better Stack with these tweaked configs. I'd be happy to assist if not 🙏
